# Generated by Django 5.0 on 2024-02-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competição',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('categoria', models.CharField(choices=[('COPA', 'copa'), ('CAMPEONATO', 'campeonato')], max_length=50)),
                ('tipo', models.CharField(choices=[('Estadual', 'Estadual'), ('Nacional', 'Nacional'), ('Internacional', 'Internacional')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano_de_fundacao', models.PositiveIntegerField(default=1970)),
                ('divisao', models.CharField(choices=[('A', 'Série A'), ('B', 'Série B'), ('C', 'Série C')], default='A', max_length=50)),
                ('genero', models.CharField(choices=[('M', 'masculino'), ('F', 'Feminino')], max_length=30)),
                ('competição', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.competição')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('posicao', models.CharField(choices=[('Atac', 'Atacante'), ('Zag', 'Zagueiro')], max_length=20)),
                ('numero', models.IntegerField(default=0)),
                ('foto', models.FileField(upload_to='')),
                ('genero', models.CharField(choices=[('M', 'masculino'), ('F', 'Feminino')], max_length=30)),
                ('Time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.time')),
            ],
        ),
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano_conquista', models.IntegerField()),
                ('colocacao', models.CharField(max_length=10)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Times', to='core.time')),
            ],
        ),
    ]
