# Generated by Django 5.0 on 2024-03-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_competição_options_alter_jogador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulos',
            name='colocacao',
            field=models.CharField(choices=[('Campeão', 'Campeão'), ('Vice-Campeão', 'Vicee-Campeão')], max_length=20),
        ),
    ]
