# Generated by Django 5.0 on 2024-02-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clube',
            new_name='Time',
        ),
        migrations.RenameField(
            model_name='jogador',
            old_name='clube',
            new_name='Time',
        ),
    ]
